### ISSUE TITLE
Implement the corporate workflow and UI

### ISSUE THREAD

**Issue by teone** [bocon13/cla-manager#10]
Worflow image to follow (@ccascone )

**Comment by ccascone** [comment]
![IMG_2888](https://user-images.githubusercontent.com/3025473/73026356-1ad28c80-3de6-11ea-9cf7-930ee82dc950.jpg)

**Comment by teone** [comment]
Started this in the [`feature/institutional-cla`](https://github.com/bocon13/cla-manager/tree/feature/institutional-cla) brach
